# Generated by Django 4.2 on 2024-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("state", models.BooleanField(default=False)),
            ],
        ),
    ]
