# Generated by Django 4.2 on 2024-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="state",
        ),
        migrations.AddField(
            model_name="url",
            name="states",
            field=models.BooleanField(default=False),
        ),
    ]
